### ISSUE TITLE
Registration to the Event PackedReceive needed

### ISSUE THREAD

**Issue by adamrak** [Papouchcom/spinel.net#1]
Hi,

According to my observation, I need to be registered to Papouch.Spinel.Spinel97.Device.Device.EventSpinelPacketReceive, to receive Events from  EventQuidoInputsChange.

Repro steps:
1. Try commenting-out QuidoDemo_CS FormMain.cs line 209 quido.OnPacketReceive += new Papouch.Spinel.Spinel97.Device.Device.EventSpinelPacketReceive(PacketReceive);
2. After connecting to the Quido and setting Autonotify and Listening to Enable, I do not receive EventQuidoInputsChange.

Best Regards,
Adam Rak

**Comment by Papouchcom** [comment]
Thanks for report. Please check our latest commit, or compiled libraries in the Last directory.

**Comment by adamrak** [comment]
Thank you for the prompt fix.
Result: Test - OK
Closing.
