### ISSUE TITLE
Enhancement: CmdSetOutputs

### ISSUE THREAD

**Issue by adamrak** [Papouchcom/spinel.net#2]
Hi,

I would appreciate to have the library extended with the CmdSetOutputs method, which will set outputs in one instruction (batch). Ideally with parameter such as List<Tuple<byte,bool>> for setting some outputs to true and others to false.

Reason for this is that setting outputs in a sequence of commands CmdSetOutput results in small time delay between particular output changes.

Thank you for understanding.

Best Regards,
Adam Rak

**Comment by Papouchcom** [comment]
Thanks for the suggestion. We added [CmdSetOutputs()](https://github.com/Papouchcom/spinel.net/wiki/Dokumentace:-Quido#cmdsetoutputs---ovl%C3%A1d%C3%A1n%C3%AD-v%C3%ADce-v%C3%BDstup%C5%AF-najednou).
